### ISSUE TITLE
Lỗi lặp từ

### ISSUE THREAD

**Issue by maytinhdibo** [vn-input/chrome-unikey#1]
Mình sử dụng bộ gõ Telex và bộ gõ làm xuất hiện các kí tự lặp lại.
Ví dụ: ví dụjudsiv

**Comment by tulequ** [comment]
cho mình xin thông tin
- ChromeOS version
- Đang dùng bàn phím ảo hay vật lý
- Mọi app điều bị như thế hay sao?
- Sau khi nhấn SPACE mới bị thế hay sao? hay lúc đang gõ đã bị rồi

**Comment by maytinhdibo** [comment]
Sau khi kiểm tra lại thì lỗi chỉ bị ở bản Chrome 69-dev. Tuy nhiên bàn phím ở bản ChromeOS 67 và 68 về bị dính dấu cách.

**Comment by tulequ** [comment]
nếu dùng phím vật lý thì ok hết
khi dùng bàn phím ảo thì không nhận được keycode nên không xử lý được
không rõ các bản cũ có chạy không vì từ trước chỉ test trên bàn phím vật lý :v
