### ISSUE TITLE
Lỗi khi bôi đen ký tự trên Chrome OS từ R93 trở đi

### ISSUE THREAD

**Issue by kiencovn** [vn-input/chrome-unikey#16]
Hi a Tuấn. Extension gõ unikey gặp vấn đề khi bôi đen ký tự và sử dụng tổ hợp phím CTRL+V, Ctrl+C hay Arrow keys. Mong a sớm fix bug này

https://user-images.githubusercontent.com/54994446/136640334-61bc2135-018a-4aa4-8505-7cb6d49eb73b.mp4

**Comment by tulequ** [comment]
phiên bản chrome mới nhất còn bị không ạ?
vì mình giờ mới quay lại dùng chromebook, và không thấy lỗi này

**Comment by kiencovn** [comment]
Em đang dùng Chrome R94 và vẫn bị lỗi này. Nơi duy nhất không bị lỗi là address bar

**Comment by tulequ** [comment]
Anh đang dùng v97 (beta) - không bị

**Comment by tulequ** [comment]
cái này khi nào a có thời gian, có thể anh sẽ liên hệ em để remote desktop debug thôi
chứ không có cách nào fix được
