### ISSUE TITLE
Bộ gõ tiếng việt trên layout bàn phím azrety

### ISSUE THREAD

**Issue by Tuananh-arsene** [vn-input/chrome-unikey#27]
chào anh, hiện tại em đang sử dụng chromebook có định dạng bàn phím azerty và khi cài đặt bộ gõ ime nó sẽ nhận là bàn phím qwerty. Không biết là mình có cách nào khắc phục hoặc có tài liệu nào để tự thêm layout vào không ạ? em cảm ơn anh

**Comment by freelancer-nguyen** [comment]
Chào bạn, mình cũng trong tình huống tương tư. Bạn có thể add layout trong manifest.json
{
      "name": "Vietnamese - Unikey (Telex)",
      "type": "ime",
      "id": "unikey-telex",
      "description": "Telex input style",
      "language": "vi",
      "layouts": ["fr"]
 }

Sau đó build lại extension

**Comment by Tuananh-arsene** [comment]
Dạ em chào anh (chị). Em đã khắc phục đc r ạm em cảm ơn anh (chị) nhiều.
Vấn đề bao lâu nay cuối cùng cũng đc giải quyết. Chúc anh (chị) ngày tốt
lành.
