### ISSUE TITLE
Google extension Manifest V3 support

### ISSUE THREAD

**Issue by freelancer-nguyen** [vn-input/chrome-unikey#28]
Chào bạn,

Mình build được extension như hướng dẫn. Nhưng khi load trong Chrome thì có 1 error nói rằng manifest version hiện là V2 và cần được migrate sang V3 (V2 sắp không được support trong năm 2023).

Mình cũng loay hoay migrate được sang V3 => đây là cái patch với những thay đổi của mình
[google-manifest-v3.zip](https://github.com/vn-input/chrome-unikey/files/11559412/google-manifest-v3.zip)

Rất mong bạn release version mới

Cảm ơn

**Comment by tulequ** [comment]
Bạn tạo luôn pull request được ko ạ?

**Comment by freelancer-nguyen** [comment]
Mình không dev trên github nên chắc phải mày mò 1 chút nhé
