### ISSUE TITLE
Liệt kê các lỗi hiện có bản 0.5.2

### ISSUE THREAD

**Issue by tuandungb** [vn-input/chrome-unikey#3]
Mình đang dùng Chrome OS 74 Beta. 
* Lỗi mất ký tự đầu trong Google sheet: Khi điền thông tin 1 cell trên google drive, ví dụ điền chữ "Tổng ..." thì khi đánh xong chữ T bước sang chữ ổ thì sẽ mất chữ T chỉ còn chữ ổ.Xóa đi viết lại thì lại ok 
* Lỗi nhảy chữ : Khi mình đánh chữ Tổng thì nó sẽ gạch chân đoạn chữ "ổng".Khi đánh xong mình click chuột về dòng khác cần sửa thì nó sẽ lôi theo chữ ổng chèn đúng vị trí mình click vào.Khi dùng linux (ibus-unikey) cũng có dạng embed gạch chân ntn thì khi mình ấn Ctrl là nó sẽ clear cái đoạn gạch chân đó thì sẽ không bị lỗi như trên nữa.

**Comment by tulequ** [comment]
> Mình đang dùng Chrome OS 74 Beta.

Mình cũng dùng bản này

> * Lỗi mất ký tự đầu trong Google sheet: Khi điền thông tin 1 cell trên google drive, ví dụ điền chữ "Tổng ..." thì khi đánh xong chữ T bước sang chữ ổ thì sẽ mất chữ T chỉ còn chữ ổ.Xóa đi viết lại thì lại ok

cái này là bệnh chung rồi, khả năng là không fix được. Vì bộ gõ mặc định cũng bị

> * Lỗi nhảy chữ : Khi mình đánh chữ Tổng thì nó sẽ gạch chân đoạn chữ "ổng".Khi đánh xong mình click chuột về dòng khác cần sửa thì nó sẽ lôi theo chữ ổng chèn đúng vị trí mình click vào.Khi dùng linux (ibus-unikey) cũng có dạng embed gạch chân ntn thì khi mình ấn Ctrl là nó sẽ clear cái đoạn gạch chân đó thì sẽ không bị lỗi như trên nữa.

Cái này thì mình test không bị, nhưng sẽ thêm cái ctrl lại vào (nhớ đã thêm rồi :D)

**Comment by tuandungb** [comment]
Nếu quả lỗi ở Google Sheet mà lỗi chung ko fix đc thì buồn thật .Vì mình thao tác office trên google sheet là chính (Thay thế Ms Office),mình nghĩ bất cứ ai dùng Chomebook thì cũng sẽ thế.

"sẽ thêm cái ctrl lại vào" => Tuyệt

**Comment by tulequ** [comment]
> Nếu quả lỗi ở Google Sheet mà lỗi chung ko fix đc thì buồn thật .Vì mình thao tác office trên google sheet là chính (Thay thế Ms Office),mình nghĩ bất cứ ai dùng Chomebook thì cũng sẽ thế.
> 
Cái này fix ở chrome 75 rồi thì phải
Máy mình test không bị nữa

**Comment by tuandungb** [comment]
Em chưa test nữa.Để em thử xem sao.Em cũng vừa update lên 75 Beta

**Comment by tulequ** [comment]
fix 0.6.0
