### ISSUE TITLE
trang cài đặt bị lỗi với với boostrap 5

### ISSUE THREAD

**Issue by tulequ** [vn-input/chrome-unikey#32]
Đơn giản có thể resolve bằng cách quay về v4

![Screenshot 2023-06-04 01 10 21](https://github.com/vn-input/chrome-unikey/assets/98257/81896ba2-428f-42ff-93c6-f3a529fbd705)

**Comment by tulequ** [comment]
@freelancer-nguyen 
nếu có thể thì bạn fix giúp mình, còn nếu ko thì mình sẽ downgrade xuống v4

**Comment by freelancer-nguyen** [comment]
@tulequ 
Mình sẽ thử. Nếu không fix được mình sẽ báo để bạn downgrade xuống v4

**Comment by freelancer-nguyen** [comment]
Mình nghĩ downgrade xuống v4 nhanh hơn :). Bạn có muốn mình tạo 1 pull request mới không?

**Comment by freelancer-nguyen** [comment]
@tulequ 
Mình nghĩ là fix được rồi
![Screenshot 2023-06-04 16 37 46](https://github.com/vn-input/chrome-unikey/assets/11617838/42610523-4c1b-4720-a947-b98316195faf)
![Screenshot 2023-06-04 16 38 51](https://github.com/vn-input/chrome-unikey/assets/11617838/b837e533-cefd-4c22-a2af-165745779ab7)
Tuy nhiên file option.js compiled hơi bị to ~350KB, so với 169KB khi dùng bootstrap v4. Mình đang xem có bỏ bớt được gì không
