### ISSUE TITLE
Lỗi khi nhập ký tự đặc biệt

### ISSUE THREAD

**Issue by freelancer-nguyen** [vn-input/chrome-unikey#34]
Chào @tulequ ,

Trên bàn phím của mình có một số phím với ký tự đặc biệt, ví dụ như `ç` `€` `£` `µ`

Khi dùng những phím trên thì unikey báo lỗi (có vẻ trong phần code wasm)

Mình có cho thêm unit test sau để tạo lại lỗi

		`it('special characters', function() {
			txtCommitted = '';
			txtComposition = '';

			var engine = 'unikey-telex';
			var c = new crxuk.ChromeUnikey(fakeChrome, libunikey);
			c.onActivate(engine);

			c.onFocus({contextID: 1});

			sendKeys(c, engine, 'ç');
			sendKeys(c, engine, '€');
			sendKeys(c, engine, '£');
			sendKeys(c, engine, 'µ');
		});`

Khi chạy make test thì có output
`Aborted(Assertion failed: Exception thrown, but exception catching is not enabled. Compile with -sNO_DISABLE_EXCEPTION_CATCHING or -sEXCEPTION_CATCHING_ALLOWED=[..] to catch.)`

Hy vọng bạn có ý tưởng để sửa, hoặc định hướng cho mình để tìm thêm. Xin cảm ơn

**Comment by freelancer-nguyen** [comment]
@tulequ , mình mày mò thêm 1 chút. Có lẽ vấn đề nằm ở trong libunikey
Mình sửa `unikey.h` & `unikey.cpp` để chuyển
` void process(unsigned char c);`
thành
` void process(unsigned int c);`

Sau đó adapt `embind.cpp` => không còn bị lỗi nữa

Mình submit pullrequest cho bạn review nhé?

**Comment by tulequ** [comment]
vâng bạn, cứ submit, rảnh mình xem

**Comment by freelancer-nguyen** [comment]
OK, mình gửi 2 pull request nhé
1. https://github.com/vn-input/libunikey/pull/1
2. https://github.com/vn-input/chrome-unikey/pull/35

**Comment by tulequ** [comment]
mình thấy rất tốt đó
nhưng khi tạo PR, mình nên tạo riêng 2 cái nếu là 2 thứ khác nhau

bạn commit lại với HEAD của libunikey nhé (do git submodule)

mà chỗ `"layouts": ["fr::fra"]`
có thể dùng chung 1 cái duy nhất là `"layouts": ["en", "fr::fra"]` không nhỉ?

**Comment by freelancer-nguyen** [comment]
Cám ơn @tulequ ,
"bạn commit lại với HEAD của libunikey nhé (do git submodule)"

Mình nghĩ là mình hiểu phải làm gì : mình phải point chrome-unikey đên HEAD của libunikey (bạn đã merge https://github.com/vn-input/libunikey/pull/1 của mình)

"mà chỗ "layouts": ["fr::fra"]
có thể dùng chung 1 cái duy nhất là "layouts": ["en", "fr::fra"] không nhỉ?"
Mình sẽ test thử xem

Từ hơn 1 tuần nay mình dùng bản unpacked, thấy rất ổn định, không còn bị error vặt nữa!

**Comment by freelancer-nguyen** [comment]
@tulequ ,
Mình gửi lại PR https://github.com/vn-input/chrome-unikey/pull/36

Về layouts trong manifest.json, mình có thử nhưng không OK. Khi đọc lại [documentation](https://developer.chrome.com/docs/extensions/mv3/manifest/input_components/) của google thì có nói rõ

> Note that ChromeOS only supports one layout per input method. If multiple layouts are specified, selection order is undefined. Extensions are therefore strongly encouraged to only specify one layout per input method.
