### ISSUE TITLE
Lỗi build docker

### ISSUE THREAD

**Issue by nkcong206** [vn-input/chrome-unikey#37]
![Screenshot 2023-06-19 00 04 14](https://github.com/vn-input/chrome-unikey/assets/56025592/d211e30b-d5b1-4008-b880-dc7f8e092ed2)
 
mình bị lỗi này, không thể build đuợc

**Comment by freelancer-nguyen** [comment]
@nkcong206 , bạn có thể thử https://github.com/vn-input/chrome-unikey#build-manual trong lúc chờ fix docker (mình build OK với phương pháp này)

**Comment by nkcong206** [comment]
@freelancer-nguyen Mình build manual được rồi còn docker kia bị lỗi vậy thôi. Thank bạn nhiều nhé!

**Comment by tulequ** [comment]
Bạn thêm dòng `#!/bin/bash` vô đầu file `docker-build` rồi thử lại nhé
