### ISSUE TITLE
Phiên bản mới trên chrome web store

### ISSUE THREAD

**Issue by freelancer-nguyen** [vn-input/chrome-unikey#39]
Mình dùng bản dev của chrome-unikey được hơn 1 tháng và thấy rất ổn định.

Mình muốn hỏi khi nào bạn sẽ release 1 version mới? Và khi nào version đó sẽ được đưa lên Chrome Web Store?

Cảm ơn!

**Comment by tulequ** [comment]
ơ mình ko thấy cái comment này
mà ngẫu nhiên mình vừa đưa lên rồi :))
